### ISSUE TITLE
Can't Install on node-red

### ISSUE THREAD

**Issue by phytondesc** [mayankraichura/node-red-contrib-sinric-ws#1]
I have tried to install with 

npm install mayankraichura/node-red-contrib-sinric-ws

But Icant see in Node Palette

**Comment by mayankraichura** [comment]
What version of OS/hardware are you using? And do you see anything in
Node-Red logs?

**Comment by phytondesc** [comment]
Hi, when update Node-Red new version, problem is solved

**Comment by mayankraichura** [comment]
Great! Thanks for the feedback.
